### ISSUE TITLE
A question about BIM

### ISSUE THREAD

**Issue by TianshengSun** [ruiyan1995/HiGCIN#1]
Hi, your work is really great. 
But, when I read the code about the skeleton (ResNet), I was confused.  
It's about the code in resNet.py.

`def feature_reshape(self, feas):`
`# (N*K, T, fea_size)`
`feas  =  feas.view(feas.size(0)//self.K, self.K, self.T,-1) #(N,K,T,fea_size)`

Does this mean that the input image has been cropped according to the player's bbox , or  you just divide the `feas.size(0)` by the number of players?

**Comment by ruiyan1995** [comment]
The input images are a sequence of personal tracklets cropped from the scene.

**Comment by TianshengSun** [comment]
Thanks a lot
